# Generated by Django 6.0.3 on 2026-04-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the month representing the billing period')),
                ('bill_given', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='cleaning_app.villa')),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('villa', 'month_year')},
            },
        ),
    ]
