# Generated by Django 6.0.4 on 2026-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15),
        ),
    ]
