# Generated by Django 6.0.3 on 2026-04-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0003_villa_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleaningRecord',
        ),
    ]
