# Generated by Django 6.0.3 on 2026-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0004_delete_cleaningrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='address',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='pool_size',
        ),
        migrations.AddField(
            model_name='villa',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
    ]
