# Generated by Django 6.0.3 on 2026-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0005_remove_villa_address_remove_villa_pool_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when the payment was actually received', null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='received_from',
            field=models.CharField(blank=True, help_text='Name of the person who made the payment', max_length=100),
        ),
    ]
