# Generated by Django 6.0.3 on 2026-04-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0006_paymentrecord_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='service_end',
            field=models.DateField(blank=True, help_text='Last billing month (1st of month)', null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='service_start',
            field=models.DateField(blank=True, help_text='First billing month (1st of month)', null=True),
        ),
    ]
