# Generated by Django 6.0.4 on 2026-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0007_villa_service_end_villa_service_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='bill_given_date',
            field=models.DateField(blank=True, help_text='Date when the bill was given', null=True),
        ),
    ]
