# Generated by Django 6.0.3 on 2026-04-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0008_paymentrecord_bill_given_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='longitude',
        ),
        migrations.AddField(
            model_name='villa',
            name='location',
            field=models.CharField(blank=True, help_text='Location details', max_length=255, null=True),
        ),
    ]
