# Generated by Django 6.0.3 on 2026-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0009_remove_villa_latitude_remove_villa_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], help_text='Mode of payment', max_length=20, null=True),
        ),
    ]
