# Generated by Django 6.0.3 on 2026-04-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0010_paymentrecord_mode_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', help_text='Mode of payment', max_length=20, null=True),
        ),
    ]
