# Generated by Django 6.0.3 on 2026-04-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0011_alter_paymentrecord_mode_of_payment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villa',
            unique_together={('phone_number', 'location')},
        ),
    ]
