# Generated by Django 6.0.3 on 2026-04-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0012_alter_villa_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='villa',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, unique=True),
        ),
    ]
