# Generated by Django 6.0.3 on 2026-07-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True, unique=True),
        ),
    ]
